Vagrant.configure("2") do |config|
    config.vm.box = "levep79/ubuntu16.04-docker"
    config.vm.network "public_network"
    config.vm.network :private_network, ip: "192.168.33.39"

    config.vm.hostname = "ansible.test"
    config.vm.provider "virtualbox" do |vb|
       vb.memory = 8000
       vb.cpus = 1
    end

    config.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "provisioning/playbook.yml"
    end
  end
